"""
Reusable MuJoCo body-Jacobian CLIK package.

This package is robot-agnostic.  It only needs a MuJoCo model/data pair and a
small serial-arm configuration that names the joints, actuators, and end
effector body/site.
"""

from control.clik.config import FFWDemoConfig, Level3AcceptanceConfig, PoseCLIKConfig
from control.clik.bimanual import (
    BimanualTargets,
    BimanualTaskStack,
    BimanualSolveResult,
    Level3AcceptanceMetrics,
    ManipulabilityState,
    NullspaceSecondaryState,
    RelativeAxisState,
    RelativeOrientationState,
    RelativePoseState,
    bimanual_object_clik_step,
    bimanual_targets_at_time,
    build_bimanual_task_stack,
    build_nullspace_secondary_state,
    adaptive_manipulability_damping,
    desired_relative_rotation,
    desired_relative_transform,
    evaluate_level3_acceptance,
    fixed_grasp_rotations,
    gripper_local_axes_for_arm,
    hand_target_from_object,
    geometric_jacobian_world,
    object_center_at_time,
    object_rotation_world,
    object_transform_at_time,
    joint_limit_barrier_velocity,
    joint_limit_margin,
    jacobian_condition_number,
    manipulability_gradient,
    relative_orientation_state,
    relative_local_axis_state,
    relative_pose_state,
    relative_z_axis_state,
    solve_bimanual_task_stack,
    solve_bimanual_task_stack_with_qp,
    solve_bimanual_task_stack_with_nullspace,
    yoshikawa_manipulability,
)
from control.clik.controller import pose_clik_step
from control.clik.gain_sweep import (
    GainSweepConfig,
    TrialTrace,
    TrialResult,
    best_results,
    make_pose_gain,
    plot_best_time_series,
    plot_metric_trends,
    plot_trial_trace,
    print_best_results,
    run_gain_sweep,
    run_pose_clik_trial,
    run_pose_clik_trial_with_trace,
    write_results_csv,
)
from control.clik.jacobian import body_jacobian, compute_full_body_jacobian
from control.clik.kinematics import (
    compute_pose_error,
    get_ee_position,
    get_ee_transform,
    make_transform,
)
from control.clik.mujoco_utils import (
    body_screw_axes_from_model,
    build_serial_arm,
    get_arm_actuator_indices,
    get_arm_joint_indices,
    make_arm_home_data,
    space_screw_axes_from_home,
)
from control.clik.orientation import normalize, rotation_from_axis_alignment
from control.clik.interception import InterceptionPlan, InterceptionPlanner
from control.clik.prediction import MovingTargetPrediction, MovingTargetPredictor
from control.clik.qp import (
    NullSpaceQPConfig,
    NullSpaceQPController,
    NullSpaceQPResult,
    QPJointVelocityConfig,
    QPJointVelocityController,
    QPJointVelocityResult,
)
from control.clik.solvers import (
    damped_least_squares,
    damped_least_squares_with_nullspace,
    damped_pseudoinverse,
    pseudoinverse,
)
from control.clik.types import SerialArm, SerialArmConfig
from control.clik.utils import (
    adjoint,
    matrix_exp_se3,
    matrix_log_se3,
    skew,
    transform_inverse,
)

__all__ = [
    "PoseCLIKConfig",
    "FFWDemoConfig",
    "Level3AcceptanceConfig",
    "BimanualTargets",
    "BimanualTaskStack",
    "BimanualSolveResult",
    "Level3AcceptanceMetrics",
    "InterceptionPlan",
    "InterceptionPlanner",
    "ManipulabilityState",
    "NullspaceSecondaryState",
    "NullSpaceQPConfig",
    "NullSpaceQPController",
    "NullSpaceQPResult",
    "MovingTargetPrediction",
    "MovingTargetPredictor",
    "QPJointVelocityConfig",
    "QPJointVelocityController",
    "QPJointVelocityResult",
    "RelativeOrientationState",
    "RelativeAxisState",
    "RelativePoseState",
    "GainSweepConfig",
    "SerialArm",
    "SerialArmConfig",
    "TrialTrace",
    "TrialResult",
    "adjoint",
    "best_results",
    "body_jacobian",
    "body_screw_axes_from_model",
    "build_serial_arm",
    "bimanual_object_clik_step",
    "bimanual_targets_at_time",
    "build_bimanual_task_stack",
    "build_nullspace_secondary_state",
    "adaptive_manipulability_damping",
    "compute_full_body_jacobian",
    "compute_pose_error",
    "damped_least_squares",
    "damped_least_squares_with_nullspace",
    "damped_pseudoinverse",
    "desired_relative_transform",
    "desired_relative_rotation",
    "evaluate_level3_acceptance",
    "fixed_grasp_rotations",
    "gripper_local_axes_for_arm",
    "hand_target_from_object",
    "geometric_jacobian_world",
    "joint_limit_barrier_velocity",
    "joint_limit_margin",
    "jacobian_condition_number",
    "manipulability_gradient",
    "get_arm_actuator_indices",
    "get_arm_joint_indices",
    "get_ee_position",
    "get_ee_transform",
    "make_transform",
    "make_pose_gain",
    "make_arm_home_data",
    "matrix_exp_se3",
    "matrix_log_se3",
    "normalize",
    "object_center_at_time",
    "object_rotation_world",
    "object_transform_at_time",
    "plot_best_time_series",
    "plot_metric_trends",
    "plot_trial_trace",
    "pose_clik_step",
    "print_best_results",
    "pseudoinverse",
    "rotation_from_axis_alignment",
    "relative_pose_state",
    "relative_orientation_state",
    "relative_local_axis_state",
    "relative_z_axis_state",
    "yoshikawa_manipulability",
    "run_gain_sweep",
    "run_pose_clik_trial",
    "run_pose_clik_trial_with_trace",
    "skew",
    "solve_bimanual_task_stack",
    "solve_bimanual_task_stack_with_qp",
    "solve_bimanual_task_stack_with_nullspace",
    "space_screw_axes_from_home",
    "transform_inverse",
    "write_results_csv",
]
